backend:
  name: github
  repo: peter-j-schmidt/dev-portfolio-blog
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: assets

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Path', name: 'path' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }